### ISSUE TITLE
Setting preset to boost doesn't work

### ISSUE THREAD

**Issue by foxy82** [ha-warmup/warmup#7]
Error when selecting boost as a preset from the front end:

`
2020-01-05 18:06:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140299356821008]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 358, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 421, in async_set_preset_mode
    await self.hass.async_add_executor_job(self.set_preset_mode, preset_mode)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/warmup/climate.py", line 218, in set_preset_mode
    raise InvalidStateError
homeassistant.exceptions.InvalidStateError
`

**Comment by foxy82** [comment]
What should we do to boost? Set to max temp for an hour? 

Set to a few degrees higher for an hour? 

Something else?

**Comment by artmg** [comment]
It appears that the override temperature is the desired floor temperature, rather than the air temperature so I think your first idea works well:
```
override_temperature = max_temp
override_duration_mins = 60
```

**Comment by foxy82** [comment]
It depends if your heating is targeting a floor or air temp I believe.

**Comment by artmg** [comment]
so if heating_target= floor then as above. If =air then +4 for an hour. We could have this as a default value for `boost_air_increase` in the config so users can override, and maybe `boost_minutes` defaulting to 60

**Comment by artmg** [comment]
Oh, and perhaps a little additional logic. If run_mode = override then duration = duration + boost_minutes, else as above. That way additional presses of boost increase the duration incrementally.

**Comment by rct** [comment]
On a related note, when the thermostat is set to override (boost) outside of the app, it does not show the mode change correctly in Home Assistant.  For me the mode changes to `auto` during override and back to `heat` when the override is complete.

**Comment by artmg** [comment]
Thanks @rct - I'm inclined to agree with your reasoning for the 'setting outside of HA' issue. However this specific traceback indicates perhaps a different problem.

So `set_preset_mode` throws an `InvalidStateError` in [line 218 of climate.py](https://github.com/ha-warmup/warmup/blob/master/warmup/climate.py#L218). So the [set_preset_mode function](https://github.com/ha-warmup/warmup/blob/master/warmup/climate.py#L204), and in fact the [return of proerty preset_mode](https://github.com/ha-warmup/warmup/blob/master/warmup/climate.py#L192), both have logic for only `Home` and `Away` modes, so disregard the fact that 
[when setting the available presets](https://github.com/ha-warmup/warmup/blob/master/warmup/climate.py#L75) it does include `Boost` mode as an option.

I am not sure how we would like into the API to see what is delivered/returned for boost mode, but I think that's the extra case that needs coding here.
